FROM node:10

# WORKDIR /Youtube_React
WORKDIR /frontend

ENV PATH /frontend/node_modules/bin:$PATH
ENV PATH /usr/local/bin/:$PATH

EXPOSE 3000


# RUN npm install -g npm@7.6.3
# RUN npm install -g create-react-app
# RUN npx start-react-app -y

# RUN chmod +x /usr/local/bin/docker-entrypoint.sh