version: "3"

services:
  backend:
    container_name: "backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/frontend
    tty: true
    ports:
      - "3000:3000"
